### ISSUE TITLE
Grieffing...

### ISSUE THREAD

**Issue by isoz** [GiantQuartz/SkyBlock#100] opened 2018-12-26 18:58 UTC
Apparently if all island members are offline and someone teleports to their island they can break everything and pvp is enabled...

**Comment by GiantQuartz** [comment] 2018-12-27 00:33
How do I reproduce this without third party plugins?

**Comment by isoz** [comment] 2018-12-27 00:36
What my players are doing is setting home in the target island and waiting for the owner to go offline and then teleporting to the island with /home.

Obviously it's logical to have teleport or homes in a skyblock server...

**Comment by isoz** [comment] 2019-01-12 12:42
This should be top priority, anyone can destroy othe islands... Why does it make the island breakable after all members log off?...

**Comment by GiantQuartz** [comment] 2019-01-12 12:54
This is not a top priority because it is not caused by SkyBlock but to external plugins. Anyway, I haven't had much time to work on SkyBlock, I will fix this as soon as I can.

**Comment by LeoBdt** [comment] 2019-02-12 06:50
Any news? any coming fix?

**Comment by GiantQuartz** [comment] 2019-02-12 09:19
This will be fixed with #121 really soon

**Comment by GiantQuartz** [comment] 2019-02-13 20:10
You can use c5d0038ecf6cbe35129902b443c205d418ced19c for this now

**Closed by GiantQuartz** 2019-02-13 20:10 UTC
Labels: Resolution: Accepted, Type: Enhancement
